import type { archComponentBlueprints as bpSchema } from "../schemas";

/**
 * Canonical blueprint catalog — the "classes" of the component system.
 *
 * Blueprint ids are app-owned (numeric, from the app registry). Each
 * definition carries a stable `key` that the app binds to an id via
 * `createAuthoringKit` — same key space as the kit bindings.
 */
export interface IBlueprintDefinition
  extends Omit<typeof bpSchema.$inferInsert, "id"> {
  /** Kit key — the app binds this to a numeric blueprint id. */
  key: string;
}

export type TBlueprintKey = IBlueprintDefinition["key"];

export const DEFAULT_BLUEPRINTS: IBlueprintDefinition[] = [
  {
    key: "table",
    name: "table",
    displayName: "$trl_bp_table",
    description: "$trl_bp_table_desc",
    slots: [
      {
        name: "columns",
        displayName: "$trl_bp_slot_columns",
        accepts: ["field-renderer", "badge", "chart-cell", "action-button"],
        grid: "flow",
        overridable: ["overrides.isHidden", "overrides.width"],
      },
      {
        name: "toolbar",
        displayName: "$trl_bp_slot_toolbar",
        accepts: ["action-button"],
        grid: "flow",
        overridable: ["overrides.label", "overrides.color"],
      },
      {
        name: "row-actions",
        displayName: "$trl_bp_slot_row_actions",
        accepts: ["action-button", "action-dropdown"],
        grid: "flow",
      },
    ],
    overridable: [
      "displayName",
      "config.settings.density",
      "config.settings.striped",
      "config.datasource.endpoint",
    ],
    contract: {
      inputs: [{ name: "tableId", required: true }],
      outputs: [
        { name: "selectedRow", type: "object" },
        { name: "selectionChanged", type: "event" },
      ],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "form",
    name: "form",
    displayName: "$trl_bp_form",
    description: "$trl_bp_form_desc",
    slots: [
      {
        name: "content",
        displayName: "$trl_bp_slot_content",
        accepts: ["field-renderer", "badge"],
        grid: "flow",
        overridable: ["overrides.isRequired", "overrides.isReadOnly"],
      },
    ],
    overridable: [
      "displayName",
      "config.settings.validateOnBlur",
      "config.settings.validateOnChange",
      "config.actions",
    ],
    contract: {
      inputs: [
        { name: "formId", required: true },
        { name: "context", required: false, defaultValue: "create" },
        { name: "recordId", required: false },
      ],
      outputs: [
        { name: "formSubmitted", type: "event" },
        { name: "formData", type: "object" },
      ],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "page",
    name: "page",
    displayName: "$trl_bp_page",
    description: "$trl_bp_page_desc",
    slots: [
      {
        name: "body",
        displayName: "$trl_bp_slot_body",
        accepts: [
          "table",
          "form",
          "pie-chart",
          "bar-chart",
          "line-chart",
          "metric",
          "info",
          "tabs",
        ],
        grid: "css-grid",
        overridable: ["grid.row", "grid.col", "grid.colSpan", "grid.rowSpan"],
      },
    ],
    overridable: ["displayName", "config.layout"],
    contract: { inputs: [], outputs: [] },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "fieldRenderer",
    name: "field-renderer",
    displayName: "$trl_bp_field_renderer",
    description: "$trl_bp_field_renderer_desc",
    slots: [],
    overridable: [
      "overrides.displayName",
      "overrides.isRequired",
      "overrides.isReadOnly",
      "overrides.placeholder",
    ],
    contract: {
      inputs: [{ name: "value", required: false }],
      outputs: [{ name: "valueChanged", type: "event" }],
    },
    category: "renderer",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "badge",
    name: "badge",
    displayName: "$trl_bp_badge",
    description: "$trl_bp_badge_desc",
    slots: [],
    overridable: ["rendererConfig.colorMap", "rendererConfig.variant"],
    contract: { inputs: [{ name: "value", required: true }], outputs: [] },
    category: "renderer",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "chartCell",
    name: "chart-cell",
    displayName: "$trl_bp_chart_cell",
    description: "$trl_bp_chart_cell_desc",
    slots: [],
    overridable: ["rendererConfig.chartType", "rendererConfig.color"],
    contract: { inputs: [{ name: "value", required: true }], outputs: [] },
    category: "renderer",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "actionButton",
    name: "action-button",
    displayName: "$trl_bp_action_button",
    description: "$trl_bp_action_button_desc",
    slots: [],
    overridable: [
      "rendererConfig.label",
      "rendererConfig.color",
      "rendererConfig.icon",
    ],
    contract: {
      inputs: [
        { name: "action", required: true },
        { name: "rowData", required: false },
      ],
      outputs: [{ name: "actionTriggered", type: "event" }],
    },
    category: "renderer",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "info",
    name: "info",
    displayName: "$trl_bp_info",
    description: "$trl_bp_info_desc",
    slots: [
      {
        name: "content",
        displayName: "$trl_bp_slot_content",
        accepts: ["field-renderer", "badge"],
        grid: "flow",
        overridable: ["overrides.isReadOnly", "overrides.displayName"],
      },
    ],
    overridable: ["displayName", "config.datasource.endpoint"],
    contract: {
      inputs: [{ name: "pathParams", required: false }],
      outputs: [{ name: "dataLoaded", type: "event" }],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "tabs",
    name: "tabs",
    displayName: "$trl_bp_tabs",
    description: "$trl_bp_tabs_desc",
    slots: [
      {
        name: "content",
        displayName: "$trl_bp_slot_content",
        accepts: ["info", "table", "form", "list", "page"],
        grid: "flow",
        overridable: ["overrides.displayName"],
      },
    ],
    overridable: ["displayName", "config.tabs"],
    contract: {
      inputs: [{ name: "pathParams", required: false }],
      outputs: [{ name: "tabChanged", type: "event" }],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "swaggerEditor",
    name: "swagger-editor",
    displayName: "$trl_bp_swagger_editor",
    description: "$trl_bp_swagger_editor_desc",
    slots: [],
    overridable: ["config.baseEndpoint"],
    contract: {
      inputs: [{ name: "pathParams", required: true }],
      outputs: [{ name: "saved", type: "event" }],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "testTab",
    name: "test-tab",
    displayName: "$trl_bp_test_tab",
    description: "$trl_bp_test_tab_desc",
    slots: [],
    overridable: [],
    contract: {
      inputs: [{ name: "pathParams", required: true }],
      outputs: [],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "perMethodPricing",
    name: "per-method-pricing",
    displayName: "$trl_bp_per_method_pricing",
    description: "$trl_bp_per_method_pricing_desc",
    slots: [],
    overridable: ["overrides.displayName"],
    contract: {
      inputs: [{ name: "pathParams", required: true }],
      outputs: [{ name: "valueChanged", type: "event" }],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "layout",
    name: "layout",
    displayName: "$trl_bp_layout",
    description: "$trl_bp_layout_desc",
    slots: [
      {
        name: "content",
        displayName: "$trl_bp_slot_content",
        accepts: [
          "table",
          "form",
          "info",
          "tabs",
          "grid",
          "stack",
          "container",
          "metric",
          "bar-chart",
          "pie-chart",
          "line-chart",
          "list",
          "page",
          "avatar",
          "logo-uploader",
          "raw-json",
          "audit-history",
          "stage-actions",
          "state-context",
          "screen-tree",
          "date-range-picker",
        ],
        grid: "flow",
        overridable: [],
      },
      {
        name: "actions",
        displayName: "$trl_bp_slot_actions",
        accepts: ["action-button"],
        grid: "flow",
        overridable: [],
      },
    ],
    overridable: ["displayName", "description", "config.title"],
    contract: { inputs: [], outputs: [] },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "button",
    name: "button",
    displayName: "$trl_bp_button",
    description: "$trl_bp_button_desc",
    slots: [],
    overridable: [
      "config.label",
      "config.type",
      "config.variant",
      "config.color",
    ],
    contract: {
      inputs: [{ name: "label", required: true }],
      outputs: [{ name: "clicked", type: "event" }],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "link",
    name: "link",
    displayName: "$trl_bp_link",
    description: "$trl_bp_link_desc",
    slots: [],
    overridable: ["config.label", "config.path", "config.variant"],
    contract: {
      inputs: [{ name: "label", required: true }],
      outputs: [{ name: "navigated", type: "event" }],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "avatar",
    name: "avatar",
    displayName: "$trl_bp_avatar",
    description: "$trl_bp_avatar_desc",
    slots: [],
    overridable: [
      "config.datasource.endpoint",
      "config.uploadEndpoint",
      "config.removeEndpoint",
      "config.avatarField",
    ],
    contract: {
      inputs: [],
      outputs: [{ name: "avatarChanged", type: "event" }],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "logoUploader",
    name: "logo-uploader",
    displayName: "$trl_bp_logo_uploader",
    description: "$trl_bp_logo_uploader_desc",
    slots: [],
    overridable: [
      "displayName",
      "config.datasource.endpoint",
      "config.uploadEndpoint",
      "config.avatarField",
      "config.uploadFieldName",
      "config.shape",
      "config.removable",
    ],
    contract: {
      inputs: [],
      outputs: [{ name: "logoChanged", type: "event" }],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "rawJson",
    name: "raw-json",
    displayName: "$trl_bp_raw_json",
    description: "$trl_bp_raw_json_desc",
    slots: [],
    overridable: ["config.queryId", "config.parameters"],
    contract: { inputs: [], outputs: [{ name: "executed", type: "event" }] },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "auditHistory",
    name: "audit-history",
    displayName: "$trl_bp_audit_history",
    description: "$trl_bp_audit_history_desc",
    slots: [],
    overridable: ["config.datasource.endpoint", "config.datasource.method"],
    contract: {
      inputs: [
        { name: "resource", required: true },
        { name: "resourceId", required: true },
      ],
      outputs: [],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "dateRangePicker",
    name: "date-range-picker",
    displayName: "$trl_date_range",
    description: "$trl_date_range_desc",
    slots: [],
    overridable: [
      "config.startLabel",
      "config.endLabel",
      "config.minDate",
      "config.maxDate",
      "config.hideQuickSelectsTab",
      "config.hideDateRangeTab",
      "config.hideFavoriteTimeButton",
    ],
    contract: {
      inputs: [
        { name: "value", required: false },
        { name: "onChange", required: false },
      ],
      outputs: [{ name: "change", type: "event" }],
    },
    category: "form",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "barChart",
    name: "bar-chart",
    displayName: "$trl_bp_bar_chart",
    description: "$trl_bp_bar_chart_desc",
    slots: [],
    overridable: [
      "displayName",
      "description",
      "config.datasource.endpoint",
      "config.datasource.method",
      "config.dataMapping.itemsPath",
      "config.dataMapping.indexKey",
      "config.dataMapping.valueKeys",
      "config.dataMapping.seriesPath",
      "config.chartOptions.margin",
      "config.chartOptions.padding",
      "config.chartOptions.axisBottom",
      "config.parameters",
    ],
    contract: {
      inputs: [{ name: "queryId", required: true }],
      outputs: [],
    },
    category: "chart",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "pieChart",
    name: "pie-chart",
    displayName: "$trl_bp_pie_chart",
    description: "$trl_bp_pie_chart_desc",
    slots: [],
    overridable: [
      "displayName",
      "config.queryId",
      "config.parameters",
      "config.dataMapping.indexKey",
      "config.dataMapping.valueKey",
    ],
    contract: {
      inputs: [{ name: "queryId", required: true }],
      outputs: [],
    },
    category: "chart",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "lineChart",
    name: "line-chart",
    displayName: "$trl_bp_line_chart",
    description: "$trl_bp_line_chart_desc",
    slots: [],
    overridable: [
      "displayName",
      "config.queryId",
      "config.parameters",
      "config.dataMapping.bucketsPath",
      "config.dataMapping.xKey",
      "config.dataMapping.yKey",
      "config.chartOptions.curve",
    ],
    contract: {
      inputs: [{ name: "queryId", required: true }],
      outputs: [],
    },
    category: "chart",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "metric",
    name: "metric",
    displayName: "$trl_bp_metric",
    description: "$trl_bp_metric_desc",
    slots: [],
    overridable: [
      "displayName",
      "config.queryId",
      "config.parameters",
      "config.dataMapping.valuePath",
      "config.dataMapping.multiplier",
      "config.dataMapping.unit",
    ],
    contract: {
      inputs: [{ name: "queryId", required: true }],
      outputs: [],
    },
    category: "chart",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "speedGauge",
    name: "speed-gauge",
    displayName: "$trl_bp_speed_gauge",
    description: "$trl_bp_speed_gauge_desc",
    slots: [],
    overridable: [
      "displayName",
      "config.queryId",
      "config.parameters",
      "config.dataMapping.valuePath",
      "config.dataMapping.unit",
    ],
    contract: {
      inputs: [{ name: "queryId", required: true }],
      outputs: [],
    },
    category: "chart",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "stateContext",
    name: "state-context",
    displayName: "$trl_bp_state_context",
    description: "$trl_bp_state_context_desc",
    slots: [
      {
        name: "content",
        displayName: "$trl_bp_slot_content",
        accepts: ["table", "form", "field-renderer", "badge"],
        grid: "flow",
        overridable: [],
      },
    ],
    overridable: ["config.name"],
    contract: {
      inputs: [{ name: "name", required: true }],
      outputs: [],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "list",
    name: "list",
    displayName: "$trl_bp_list",
    description: "$trl_bp_list_desc",
    slots: [],
    overridable: [
      "displayName",
      "config.datasource.endpoint",
      "config.toolbarActions",
      "config.rowActions",
    ],
    contract: {
      inputs: [{ name: "pathParams", required: false }],
      outputs: [],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "screenTree",
    name: "screen-tree",
    displayName: "$trl_bp_screen_tree",
    description: "$trl_bp_screen_tree_desc",
    slots: [],
    overridable: ["config.datasource.endpoint", "config.datasource.params"],
    contract: {
      inputs: [{ name: "screenId", required: true }],
      outputs: [],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "stageActions",
    name: "stage-actions",
    displayName: "$trl_bp_stage_actions",
    description: "$trl_bp_stage_actions_desc",
    slots: [],
    overridable: ["displayName"],
    contract: { inputs: [], outputs: [] },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  // ── Explicit layout primitives (MUI-aligned) ──────────────────
  {
    key: "grid",
    name: "grid",
    displayName: "$trl_bp_grid",
    description: "$trl_bp_grid_desc",
    slots: [
      {
        name: "content",
        displayName: "$trl_bp_slot_content",
        accepts: [
          "grid",
          "table",
          "form",
          "info",
          "tabs",
          "metric",
          "bar-chart",
          "pie-chart",
          "line-chart",
          "list",
          "page",
          "avatar",
          "logo-uploader",
          "raw-json",
          "audit-history",
          "stage-actions",
          "state-context",
          "screen-tree",
          "date-range-picker",
        ],
        grid: "flow",
        overridable: [
          "config.container",
          "config.spacing",
          "config.direction",
          "config.sizes",
          "config.offset",
          "config.order",
        ],
      },
    ],
    overridable: [
      "displayName",
      "config.container",
      "config.spacing",
      "config.direction",
      "config.sizes",
      "config.offset",
    ],
    contract: { inputs: [], outputs: [] },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "stack",
    name: "stack",
    displayName: "$trl_bp_stack",
    description: "$trl_bp_stack_desc",
    slots: [
      {
        name: "content",
        displayName: "$trl_bp_slot_content",
        accepts: [
          "table",
          "form",
          "info",
          "tabs",
          "grid",
          "stack",
          "container",
          "metric",
          "bar-chart",
          "pie-chart",
          "line-chart",
          "list",
          "page",
          "avatar",
          "logo-uploader",
          "raw-json",
          "audit-history",
          "stage-actions",
          "state-context",
          "screen-tree",
          "date-range-picker",
        ],
        grid: "flow",
        overridable: ["config.direction", "config.spacing"],
      },
    ],
    overridable: ["displayName", "config.direction", "config.spacing"],
    contract: { inputs: [], outputs: [] },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
  {
    key: "container",
    name: "container",
    displayName: "$trl_bp_container",
    description: "$trl_bp_container_desc",
    slots: [
      {
        name: "content",
        displayName: "$trl_bp_slot_content",
	        accepts: [
	          "table",
	          "form",
	          "info",
	          "tabs",
	          "box",
	          "grid",
	          "stack",
	          "container",
	          "paper",
	          "metric",
	          "bar-chart",
	          "pie-chart",
	          "line-chart",
	          "list",
	          "page",
	          "avatar",
	          "logo-uploader",
	          "raw-json",
	          "audit-history",
	          "stage-actions",
	          "state-context",
	          "screen-tree",
	          "date-range-picker",
	        ],
	        grid: "flow",
	        overridable: ["config.maxWidth", "config.disableGutters"],
	      },
	    ],
	    overridable: ["displayName", "config.maxWidth", "config.disableGutters"],
	    contract: { inputs: [], outputs: [] },
	    category: "core",
	    isActive: true,
	    isSystem: true,
	    meta: null,
	  },
	  {
	    key: "box",
	    name: "box",
	    displayName: "$trl_bp_box",
	    description: "$trl_bp_box_desc",
	    slots: [
	      {
	        name: "content",
	        displayName: "$trl_bp_slot_content",
	        accepts: [
	          "table",
	          "form",
	          "info",
	          "tabs",
	          "box",
	          "grid",
	          "stack",
	          "container",
	          "paper",
	          "metric",
	          "bar-chart",
	          "pie-chart",
	          "line-chart",
	          "list",
	          "page",
	          "avatar",
	          "logo-uploader",
	          "raw-json",
	          "audit-history",
	          "stage-actions",
	          "state-context",
	          "screen-tree",
	          "date-range-picker",
	        ],
	        grid: "flow",
	        overridable: ["config.display", "config.padding", "config.gap"],
	      },
	    ],
	    overridable: ["displayName", "config.display", "config.padding"],
	    contract: { inputs: [], outputs: [] },
	    category: "core",
	    isActive: true,
	    isSystem: true,
	    meta: null,
	  },
	  {
	    key: "paper",
	    name: "paper",
	    displayName: "$trl_bp_paper",
	    description: "$trl_bp_paper_desc",
	    slots: [
	      {
	        name: "content",
	        displayName: "$trl_bp_slot_content",
	        accepts: [
	          "table",
	          "form",
	          "info",
	          "tabs",
	          "box",
	          "grid",
	          "stack",
	          "container",
	          "paper",
	          "metric",
	          "bar-chart",
	          "pie-chart",
	          "line-chart",
	          "list",
	          "page",
	          "avatar",
	          "logo-uploader",
	          "raw-json",
	          "audit-history",
	          "stage-actions",
	          "state-context",
	          "screen-tree",
	          "date-range-picker",
	        ],
	        grid: "flow",
	        overridable: ["config.elevation", "config.variant", "config.padding"],
	      },
	    ],
    overridable: [
      "displayName",
      "config.elevation",
      "config.variant",
      "config.padding",
    ],
	    contract: { inputs: [], outputs: [] },
	    category: "core",
	    isActive: true,
	    isSystem: true,
	    meta: null,
	  },
	  {
	    key: "typography",
	    name: "typography",
	    displayName: "$trl_bp_typography",
	    description: "$trl_bp_typography_desc",
	    slots: [],
    overridable: [
      "config.text",
      "config.variant",
      "config.align",
      "config.color",
    ],
	    contract: { inputs: [{ name: "text", required: true }], outputs: [] },
	    category: "core",
	    isActive: true,
	    isSystem: true,
	    meta: null,
	  },
  {
    // Tenant wallet (Billing → Wallet). App-owned renderer: balance header,
    // deposit form and the transaction ledger.
    key: "walletStore",
    name: "walletStore",
    displayName: "$trl_bp_wallet_store",
    description: "$trl_bp_wallet_store_desc",
    slots: [],
    overridable: ["displayName"],
    contract: {
      inputs: [{ name: "pathParams", required: false }],
      outputs: [],
    },
    category: "core",
    isActive: true,
    isSystem: true,
    meta: null,
  },
];
