// ──────────────────────────────────────────────────────────────────
// @wrk-t/nestjs-metadata/authoring — public surface.
//
// Kept OUT of the main src/index.ts barrel so authoring code is never
// pulled into the runtime bundle. Imported only by seed files.
// ──────────────────────────────────────────────────────────────────

export {
	registerBlueprintIds,
	getBlueprintId,
	createBlueprintRows,
} from "./registry";
export { SeedContext, resetElementIdSequence } from "./compile";
export type { SeedBundle } from "./compile";
export { DEFAULT_BLUEPRINTS } from "./blueprints";
export type { IBlueprintDefinition, TBlueprintKey } from "./blueprints";
	export {
	ActionButton,
	AuditHistory,
	AuthoringNode,
	AutocompleteField,
	Avatar,
	Badge,
	BarChart,
	BooleanField,
	Box,
	Button,
	ChartCell,
	CheckboxField,
	ColorField,
	Component,
	Container,
	DateField,
	DateTimeField,
	DateRangePicker,
	EmailField,
	FieldNode,
	FieldRenderer,
	Form,
	Grid,
	Info,
	JsonField,
	Layout,
	LineChart,
	Link,
	List,
	LogoUploader,
	Metric,
	MultiselectField,
	NumberField,
	Page,
	Paper,
	PasswordField,
	PerMethodPricing,
	PieChart,
	RadioField,
	RawJson,
	Renderer,
	Screen,
	ScreenTree,
	SelectField,
	SpeedGauge,
	Stack,
	StageActions,
	StateContext,
	SwaggerEditor,
	SwitchField,
	Table,
	Tabs,
	TestTab,
	TextareaField,
	TextField,
	TimeField,
	Typography,
	normalizeChildren,
} from "./nodes";
export type { AuthoringChild, Children, IComponentIdentity } from "./nodes";
export type { IScreenIdentity } from "./nodes";
export type { IEditOp, TEditOperation } from "../schemas";
	export type {
	FieldDatasource,
	FieldDefRow,
	FieldType,
	FieldValidations,
	IAuditHistoryConfig,
	IAvatarConfig,
	IBoxConfig,
	IButtonCondition,
	IButtonConfig,
	IButtonConfirm,
	IButtonDialog,
	IChartConfig,
	IColumnConfig,
	IContainerConfig,
	IDateRangePickerConfig,
	IFieldConfig,
	IFormConfig,
	IFormSubmitConfig,
	IGridConfig,
	IInfoConfig,
	ILayoutConfig,
	ILinkConfig,
	IListConfig,
	ILogoUploaderConfig,
	IPaperConfig,
	IPerMethodPricingConfig,
	IRawJsonConfig,
	IScreenTreeConfig,
	IStackConfig,
	IStageActionsConfig,
	IStateContextConfig,
	ISwaggerEditorConfig,
	ITableConfig,
	ITableOnRowClick,
	ITabsConfig,
	ITestTabConfig,
	ITypographyConfig,
} from "./config-types";
